WITH MARCH AS(
    SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) = 10
)
SELECT  CAR.CAR_ID FROM MARCH
JOIN CAR_RENTAL_COMPANY_CAR AS CAR
WHERE MARCH.CAR_ID = CAR.CAR_ID AND CAR.CAR_TYPE = "세단"
GROUP BY CAR.CAR_ID
ORDER BY CAR.CAR_ID DESC;